FROM python:3.9-alpine

RUN apk add --update --no-cache git
RUN mkdir /app
COPY . /app
WORKDIR /app/Go-Simp/service/web
RUN pip install -r requirements.txt

EXPOSE 8000
CMD ["gunicorn", "Go_simpsPy.wsgi:application", "--bind", "0.0.0.0:8000"]