FROM python:alpine

RUN apk add --update --no-cache git
RUN mkdir /app
WORKDIR /app
RUN git clone --single-branch --branch main https://github.com/JustHumanz/Go-Simp
WORKDIR Go-Simp/service/web
RUN git checkout main
RUN pip install -r requirements.txt

EXPOSE 8000
CMD ["gunicorn", "Go_simpsPy.wsgi:application", "--bind", "0.0.0.0:8000"]