image: docker:stable

stages:
  - build
  - deploy

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_DRIVER: overlay2

services:
  - docker:19.03.12-dind

before_script:
  - docker info
  - apk update
  - apk upgrade
  - apk add python python-dev py-pip build-base
  - pip install docker-compose

include:
  - template: Code-Quality.gitlab-ci.yml

build go-simp service:
  stage: build
  before_script:
    - $COMPOSE > $CI_PROJECT_DIR/docker-compose.yaml
    - $CONFIG > $CI_PROJECT_DIR/config.toml
    - $env > $CI_PROJECT_DIR/.env
    - docker-compose build
  script:
    - docker-compose build
  
code_quality:
  stage: build  
  artifacts:
    paths: [gl-code-quality-report.json]

deploy go-simp:
  stage: deploy
  script:
    - >
      if [ "$MIGRATE" == "true" ]; then
        docker-compose up db_migrate livestream && docker-compose up -d && docker-compose stop db_migrate
      else
        docker-compose up -d && docker-compose stop db_migrate
      fi      
  when: manual
