image: docker:19.03.12

services:
  - docker:19.03.12-dind

stages:
  - init
  - build
  - deploy

build go-simp:
  stage: init
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker info
  script:
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  tags:
    - docker
    - gce    
  only:
    - master    


build pilot:
  stage: build
  only:
    - tags      
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker info  
  script:
    - docker pull $CI_REGISTRY_IMAGE
    - docker tag $CI_REGISTRY_IMAGE go-simp
    - docker build -t pilot $CI_PROJECT_DIR/service/pilot
    - docker tag pilot "$CI_REGISTRY_IMAGE"/pilot:"$CI_COMMIT_TAG"
    - docker push "$CI_REGISTRY_IMAGE"/pilot:"$CI_COMMIT_TAG"
  tags:
    - docker
    - gce    

build migrate:
  stage: build
  only:
    - tags   
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker info  
  script:
    - docker pull $CI_REGISTRY_IMAGE
    - docker tag $CI_REGISTRY_IMAGE go-simp
    - docker build -t migrate $CI_PROJECT_DIR/service/migrate
    - docker tag migrate "$CI_REGISTRY_IMAGE"/migrate
    - docker push "$CI_REGISTRY_IMAGE"/migrate
  tags:
    - docker
    - gce    

build fanart:
  stage: build
  only:
    - tags      
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker info   
  script:
    - docker pull $CI_REGISTRY_IMAGE
    - docker tag $CI_REGISTRY_IMAGE go-simp
    - docker build -t fanart $CI_PROJECT_DIR/service/fanart
    - docker tag fanart "$CI_REGISTRY_IMAGE"/fanart:"$CI_COMMIT_TAG"
    - docker push "$CI_REGISTRY_IMAGE"/fanart:"$CI_COMMIT_TAG"
  tags:
    - docker
    - gce        

build livestream:
  stage: build
  only:
    - tags      
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker info   
  script:
    - docker pull $CI_REGISTRY_IMAGE
    - docker tag $CI_REGISTRY_IMAGE go-simp
    - docker build -t livestream $CI_PROJECT_DIR/service/livestream
    - docker tag livestream "$CI_REGISTRY_IMAGE"/livestream:"$CI_COMMIT_TAG"
    - docker push "$CI_REGISTRY_IMAGE"/livestream:"$CI_COMMIT_TAG"
  tags:
    - docker
    - gce        

build subscriber:
  stage: build
  only:
    - tags      
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker info   
  script:
    - docker pull $CI_REGISTRY_IMAGE
    - docker tag $CI_REGISTRY_IMAGE go-simp
    - docker build -t subscriber $CI_PROJECT_DIR/service/subscriber
    - docker tag subscriber "$CI_REGISTRY_IMAGE"/subscriber:"$CI_COMMIT_TAG"
    - docker push "$CI_REGISTRY_IMAGE"/subscriber:"$CI_COMMIT_TAG"   
  tags:
    - docker
    - gce        

build utility:
  stage: build
  only:
    - tags      
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker info   
  script:
    - docker pull $CI_REGISTRY_IMAGE
    - docker tag $CI_REGISTRY_IMAGE go-simp
    - docker build -t utility $CI_PROJECT_DIR/service/utility
    - docker tag utility "$CI_REGISTRY_IMAGE"/utility:"$CI_COMMIT_TAG"
    - docker push "$CI_REGISTRY_IMAGE"/utility:"$CI_COMMIT_TAG"       
  tags:
    - docker
    - gce        

build frontend:
  stage: build
  only:
    - tags      
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker info   
  script:
    - docker pull $CI_REGISTRY_IMAGE
    - docker tag $CI_REGISTRY_IMAGE go-simp
    - docker build -t frontend $CI_PROJECT_DIR/service/frontend
    - docker tag frontend "$CI_REGISTRY_IMAGE"/frontend:"$CI_COMMIT_TAG"
    - docker push "$CI_REGISTRY_IMAGE"/frontend:"$CI_COMMIT_TAG"        
  tags:
    - docker
    - gce        

build guild:
  stage: build
  only:
    - tags      
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker info   
  script:
    - docker pull $CI_REGISTRY_IMAGE
    - docker tag $CI_REGISTRY_IMAGE go-simp
    - docker build -t guild $CI_PROJECT_DIR/service/guild
    - docker tag guild "$CI_REGISTRY_IMAGE"/guild:"$CI_COMMIT_TAG"
    - docker push "$CI_REGISTRY_IMAGE"/guild:"$CI_COMMIT_TAG"  
  tags:
    - docker
    - gce        

build rest_api:
  stage: build
  only:
    - tags      
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker info   
  script:
    - docker pull $CI_REGISTRY_IMAGE
    - docker tag $CI_REGISTRY_IMAGE go-simp    
    - docker build -t api $CI_PROJECT_DIR/service/rest-api
    - docker tag api "$CI_REGISTRY_IMAGE"/api:"$CI_COMMIT_TAG"
    - docker push "$CI_REGISTRY_IMAGE"/api:"$CI_COMMIT_TAG"
  tags:
    - docker
    - gce        

build static_files:
  stage: build     
  only:
    - tags   
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker info   
  script:
    - docker build -t static_files $CI_PROJECT_DIR/Img
    - docker tag static_files "$CI_REGISTRY_IMAGE"/static_files
    - docker push "$CI_REGISTRY_IMAGE"/static_files
  tags:
    - docker
    - gce        

build web:
  stage: build   
  only:
    - tags   
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker info   
  script:
    - docker build -t web $CI_PROJECT_DIR/service/web
    - docker tag web "$CI_REGISTRY_IMAGE"/web
    - docker push "$CI_REGISTRY_IMAGE"/web
  tags:
    - docker
    - gce                

build multitor:
  stage: build     
  only:
    - tags   
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker info   
  script:
    - docker build -t multitor $CI_PROJECT_DIR/service/multitor/
    - docker tag multitor "$CI_REGISTRY_IMAGE"/multitor
    - docker push "$CI_REGISTRY_IMAGE"/multitor
  tags:
    - docker
    - gce            


deploy:
  image: alpine:latest
  stage: deploy
  only:
    - tags      
  script:
    - apk update  && apk add --no-cache curl
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
    - chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl
    - mkdir -p $HOME/.kube
    - echo -n ${KUBE_CONFIG} | base64 -d > $HOME/.kube/config
    - kubectl config get-contexts
    - kubectl --record deployment.apps/go-simp-fanart set image deployment.v1.apps/go-simp-fanart fanart=registry.gitlab.com/justhumanz/go-simp/fanart:"$CI_COMMIT_TAG"
    - kubectl set env deployment/go-simp-frontend VERSION="$CI_COMMIT_TAG"
    - kubectl --record deployment.apps/go-simp-frontend set image deployment.v1.apps/go-simp-frontend frontend=registry.gitlab.com/justhumanz/go-simp/frontend:"$CI_COMMIT_TAG"
    - kubectl --record deployment.apps/go-simp-guild set image deployment.v1.apps/go-simp-guild guild=registry.gitlab.com/justhumanz/go-simp/guild:"$CI_COMMIT_TAG"
    - kubectl --record deployment.apps/go-simp-live set image deployment.v1.apps/go-simp-live livestream=registry.gitlab.com/justhumanz/go-simp/livestream:"$CI_COMMIT_TAG"
    - kubectl --record deployment.apps/go-simp-pilot set image deployment.v1.apps/go-simp-pilot pilot=registry.gitlab.com/justhumanz/go-simp/pilot:"$CI_COMMIT_TAG"
    - kubectl --record deployment.apps/go-simp-subscriber set image deployment.v1.apps/go-simp-subscriber subscriber=registry.gitlab.com/justhumanz/go-simp/subscriber:"$CI_COMMIT_TAG"
    - kubectl --record deployment.apps/go-simp-utility set image deployment.v1.apps/go-simp-utility utility=registry.gitlab.com/justhumanz/go-simp/utility:"$CI_COMMIT_TAG"
    - kubectl rollout restart deployment.apps/go-simp-web
  tags:
    - k8s    
  when: manual  
