image: docker:stable

stages:
  - build
  - deploy

variables:
  # When using dind service, we need to instruct docker to talk with
  # the daemon started inside of the service. The daemon is available
  # with a network connection instead of the default
  # /var/run/docker.sock socket. Docker 19.03 does this automatically
  # by setting the DOCKER_HOST in
  # https://github.com/docker-library/docker/blob/d45051476babc297257df490d22cbd806f1b11e4/19.03/docker-entrypoint.sh#L23-L29
  #
  # The 'docker' hostname is the alias of the service container as described at
  # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#accessing-the-services.
  #
  # Specify to Docker where to create the certificates, Docker will
  # create them automatically on boot, and will create
  # `/certs/client` that will be shared between the service and job
  # container, thanks to volume mount from config.toml
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:19.03.12-dind

before_script:
  - docker info

include:
  - template: Code-Quality.gitlab-ci.yml

code_quality:
  stage: build  
  artifacts:
    paths: [gl-code-quality-report.json]

build go-simp 1/10:
  stage: build
  script:
    - docker build -t mainbot .

build go-simp 2/10:
  stage: build
  script:
    - docker build -t migrate ./service/backend/db_migrate

build go-simp 3/10:
  stage: build
  script:
    - docker build -t fanart ./service/backend/fanart    

build go-simp 4/10:
  stage: build
  script:
    - docker build -t livestream ./service/backend/livestream

build go-simp 5/10:
  stage: build
  script:
    - docker build -t subscriber ./service/backend/subscriber

build go-simp 6/10:
  stage: build
  script:
    - docker build -t utility ./service/backend/utility

build go-simp 7/10:
  stage: build
  script:
    - docker build -t frontend ./service/frontend

build go-simp 8/10:
  stage: build
  script:
    - docker build -t guild ./service/guild

build go-simp 9/10:
  stage: build
  script:
    - docker build -t web ./service/web

build go-simp 10/10:
  stage: build
  script:
    - docker build -t rest-api ./service/rest-api