stages:
  - build
  - deploy
  
build go-simp 1/10:
  image: docker:latest
  stage: build
  include:
    - template: Code-Quality.gitlab-ci.yml
  script:
    - docker build -t mainbot .

build go-simp 2/10:
  image: docker:latest
  stage: build
  script:
    - docker build -t migrate ./service/backend/db_migrate

build go-simp 3/10:
  image: docker:latest
  stage: build
  script:
    - docker build -t fanart ./service/backend/fanart    

build go-simp 4/10:
  image: docker:latest
  stage: build
  script:
    - docker build -t livestream ./service/backend/livestream

build go-simp 5/10:
  image: docker:latest
  stage: build
  script:
    - docker build -t subscriber ./service/backend/subscriber

build go-simp 6/10:
  image: docker:latest
  stage: build
  script:
    - docker build -t utility ./service/backend/utility

build go-simp 7/10:
  image: docker:latest
  stage: build
  script:
    - docker build -t frontend ./service/frontend

build go-simp 8/10:
  image: docker:latest
  stage: build
  script:
    - docker build -t guild ./service/guild

build go-simp 9/10:
  image: docker:latest
  stage: build
  script:
    - docker build -t web ./service/web

build go-simp 10/10:
  image: docker:latest
  stage: build
  script:
    - docker build -t rest-api ./service/rest-api

    