image: docker:stable

stages:
  - build
  - deploy

before_script:
  - docker info
  - apk add --no-cache docker-compose  
  - cp /data/docker-compose-prod.yaml $CI_PROJECT_DIR/docker-compose.prod.yaml
  - cp /data/config.toml $CI_PROJECT_DIR/config.toml
  - cp /data/.env $CI_PROJECT_DIR/.env
include:
  - template: Code-Quality.gitlab-ci.yml

build go-simp service:
  stage: build
  tags:
    - build
  script:
    - docker-compose -f docker-compose.prod.yaml build
  
code_quality:
  stage: build  
  tags:
    - gitlab-org-docker   
  artifacts:
    paths: [gl-code-quality-report.json]

deploy go-simp:
  stage: deploy
  tags:
    - deploy  
  script:
    - >
      if [ "$MIGRATE" == "true" ]; then
        docker-compose -f docker-compose.prod.yaml up db_migrate livestream && docker-compose -f docker-compose.prod.yaml up -d && docker-compose -f docker-compose.prod.yaml stop db_migrate
      else
        docker-compose -f docker-compose.prod.yaml up -d && docker-compose -f docker-compose.prod.yaml stop db_migrate
      fi      
  when: manual
