image: docker:stable

stages:
  - build
  - deploy

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_DRIVER: overlay2

services:
  - docker:19.03.12-dind

before_script:
  - docker info

include:
  - template: Code-Quality.gitlab-ci.yml

build go-simp service:
  stage: build
  before_script:
    - apk add --no-cache docker-compose
    - cp /data/docker-compose-prod.yaml $CI_PROJECT_DIR/docker-compose.prod.yaml
    - cp /data/config.toml $CI_PROJECT_DIR/config.toml
    - cp /data/.env > $CI_PROJECT_DIR/.env
    - docker-compose -f docker-compose.prod.yaml build
  script:
    - docker-compose build
  
code_quality:
  stage: build  
  artifacts:
    paths: [gl-code-quality-report.json]

deploy go-simp:
  stage: deploy
  before_script:
    - apk add --no-cache docker-compose
  script:
    - >
      if [ "$MIGRATE" == "true" ]; then
        docker-compose -f docker-compose.prod.yaml up db_migrate livestream && docker-compose -f docker-compose.prod.yaml up -d && docker-compose -f docker-compose.prod.yaml stop db_migrate
      else
        docker-compose -f docker-compose.prod.yaml up -d && docker-compose -f docker-compose.prod.yaml stop db_migrate
      fi      
  when: manual
