image: docker:19.03.12

services:
  - docker:19.03.12-dind

stages:
  - init
  - build
  - deploy

build go-simp:
  stage: init
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker info
  script:
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  tags:
    - docker
    - gce    
  only:
    - master    


build pilot:
  stage: build
  only:
    - tags      
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker info  
  script:
    - docker pull $CI_REGISTRY_IMAGE
    - docker tag $CI_REGISTRY_IMAGE go-simp
    - docker build -t pilot $CI_PROJECT_DIR/service/pilot
    - docker tag pilot "$CI_REGISTRY_IMAGE"/pilot:"$CI_COMMIT_TAG"
    - docker push "$CI_REGISTRY_IMAGE"/pilot:"$CI_COMMIT_TAG"
  tags:
    - docker
    - gce    

build migrate:
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker info  
  script:
    - docker pull $CI_REGISTRY_IMAGE
    - docker tag $CI_REGISTRY_IMAGE go-simp
    - docker build -t migrate $CI_PROJECT_DIR/service/migrate
    - docker tag migrate "$CI_REGISTRY_IMAGE"/migrate
    - docker push "$CI_REGISTRY_IMAGE"/migrate
  tags:
    - docker
    - gce    
  only:
    - master  
    
build twitter fanart:
  stage: build
  only:
    - tags      
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker info   
  script:
    - docker pull $CI_REGISTRY_IMAGE
    - docker tag $CI_REGISTRY_IMAGE go-simp
    - docker build -t fanart $CI_PROJECT_DIR/service/fanart/twitter
    - docker tag fanart "$CI_REGISTRY_IMAGE"/fanart-twitter:"$CI_COMMIT_TAG"
    - docker push "$CI_REGISTRY_IMAGE"/fanart-twitter:"$CI_COMMIT_TAG"
  tags:
    - docker
    - gce        

build bilibili fanart:
  stage: build
  only:
    - tags      
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker info   
  script:
    - docker pull $CI_REGISTRY_IMAGE
    - docker tag $CI_REGISTRY_IMAGE go-simp
    - docker build -t fanart $CI_PROJECT_DIR/service/fanart/bilibili
    - docker tag fanart "$CI_REGISTRY_IMAGE"/fanart-bilibili:"$CI_COMMIT_TAG"
    - docker push "$CI_REGISTRY_IMAGE"/fanart-bilibili:"$CI_COMMIT_TAG"
  tags:
    - docker
    - gce         

build pixiv fanart:
  stage: build
  only:
    - tags      
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker info   
  script:
    - docker pull $CI_REGISTRY_IMAGE
    - docker tag $CI_REGISTRY_IMAGE go-simp
    - docker build -t fanart $CI_PROJECT_DIR/service/fanart/pixiv
    - docker tag fanart "$CI_REGISTRY_IMAGE"/fanart-pixiv:"$CI_COMMIT_TAG"
    - docker push "$CI_REGISTRY_IMAGE"/fanart-pixiv:"$CI_COMMIT_TAG"
  tags:
    - docker
    - gce      

build youtube livestream:
  stage: build
  only:
    - tags      
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker info   
  script:
    - docker pull $CI_REGISTRY_IMAGE
    - docker tag $CI_REGISTRY_IMAGE go-simp
    - docker build -t livestream $CI_PROJECT_DIR/service/livestream/youtube
    - docker tag livestream "$CI_REGISTRY_IMAGE"/youtube-livestream:"$CI_COMMIT_TAG"
    - docker push "$CI_REGISTRY_IMAGE"/youtube-livestream:"$CI_COMMIT_TAG"
  tags:
    - docker
    - gce        

build spacebili livestream:
  stage: build
  only:
    - tags      
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker info   
  script:
    - docker pull $CI_REGISTRY_IMAGE
    - docker tag $CI_REGISTRY_IMAGE go-simp
    - docker build -t livestream $CI_PROJECT_DIR/service/livestream/bilibili/space
    - docker tag livestream "$CI_REGISTRY_IMAGE"/spacebili-livestream:"$CI_COMMIT_TAG"
    - docker push "$CI_REGISTRY_IMAGE"/spacebili-livestream:"$CI_COMMIT_TAG"
  tags:
    - docker
    - gce        

build livebili livestream:
  stage: build
  only:
    - tags      
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker info   
  script:
    - docker pull $CI_REGISTRY_IMAGE
    - docker tag $CI_REGISTRY_IMAGE go-simp
    - docker build -t livestream $CI_PROJECT_DIR/service/livestream/bilibili/live
    - docker tag livestream "$CI_REGISTRY_IMAGE"/livebili-livestream:"$CI_COMMIT_TAG"
    - docker push "$CI_REGISTRY_IMAGE"/livebili-livestream:"$CI_COMMIT_TAG"
  tags:
    - docker
    - gce        

build twitch livestream:
  stage: build
  only:
    - tags      
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker info   
  script:
    - docker pull $CI_REGISTRY_IMAGE
    - docker tag $CI_REGISTRY_IMAGE go-simp
    - docker build -t livestream $CI_PROJECT_DIR/service/livestream/twitch
    - docker tag livestream "$CI_REGISTRY_IMAGE"/twitch-livestream:"$CI_COMMIT_TAG"
    - docker push "$CI_REGISTRY_IMAGE"/twitch-livestream:"$CI_COMMIT_TAG"
  tags:
    - docker
    - gce        

build subscriber:
  stage: build
  only:
    - tags      
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker info   
  script:
    - docker pull $CI_REGISTRY_IMAGE
    - docker tag $CI_REGISTRY_IMAGE go-simp
    - docker build -t subscriber $CI_PROJECT_DIR/service/subscriber
    - docker tag subscriber "$CI_REGISTRY_IMAGE"/subscriber:"$CI_COMMIT_TAG"
    - docker push "$CI_REGISTRY_IMAGE"/subscriber:"$CI_COMMIT_TAG"   
  tags:
    - docker
    - gce        

build utility:
  stage: build
  only:
    - tags      
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker info   
  script:
    - docker pull $CI_REGISTRY_IMAGE
    - docker tag $CI_REGISTRY_IMAGE go-simp
    - docker build -t utility $CI_PROJECT_DIR/service/utility
    - docker tag utility "$CI_REGISTRY_IMAGE"/utility:"$CI_COMMIT_TAG"
    - docker push "$CI_REGISTRY_IMAGE"/utility:"$CI_COMMIT_TAG"       
  tags:
    - docker
    - gce        

build frontend:
  stage: build
  only:
    - tags      
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker info   
  script:
    - docker pull $CI_REGISTRY_IMAGE
    - docker tag $CI_REGISTRY_IMAGE go-simp
    - docker build -t frontend $CI_PROJECT_DIR/service/frontend
    - docker tag frontend "$CI_REGISTRY_IMAGE"/frontend:"$CI_COMMIT_TAG"
    - docker push "$CI_REGISTRY_IMAGE"/frontend:"$CI_COMMIT_TAG"        
  tags:
    - docker
    - gce        

build guild:
  stage: build
  only:
    - tags      
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker info   
  script:
    - docker pull $CI_REGISTRY_IMAGE
    - docker tag $CI_REGISTRY_IMAGE go-simp
    - docker build -t guild $CI_PROJECT_DIR/service/guild
    - docker tag guild "$CI_REGISTRY_IMAGE"/guild:"$CI_COMMIT_TAG"
    - docker push "$CI_REGISTRY_IMAGE"/guild:"$CI_COMMIT_TAG"  
  tags:
    - docker
    - gce        

build rest_api:
  stage: build
  only:
    - tags      
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker info   
  script:
    - docker pull $CI_REGISTRY_IMAGE
    - docker tag $CI_REGISTRY_IMAGE go-simp    
    - docker build -t api $CI_PROJECT_DIR/service/rest-api
    - docker tag api "$CI_REGISTRY_IMAGE"/api:"$CI_COMMIT_TAG"
    - docker push "$CI_REGISTRY_IMAGE"/api:"$CI_COMMIT_TAG"
  tags:
    - docker
    - gce        

build static_files:
  stage: build     
  only:
    - tags   
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker info   
  script:
    - docker build -t static_files $CI_PROJECT_DIR/Img
    - docker tag static_files "$CI_REGISTRY_IMAGE"/static_files
    - docker push "$CI_REGISTRY_IMAGE"/static_files
  tags:
    - docker
    - gce        

build web:
  stage: build   
  only:
    - tags   
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker info   
  script:
    - docker build -t web $CI_PROJECT_DIR/service/web
    - docker tag web "$CI_REGISTRY_IMAGE"/web
    - docker push "$CI_REGISTRY_IMAGE"/web
  tags:
    - docker
    - gce                

deploy:
  image: alpine:latest
  stage: deploy
  only:
    - tags      
  script:
    - apk update  && apk add --no-cache curl
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
    - chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl
    - mkdir -p $HOME/.kube
    - echo -n ${KUBE_CONFIG} | base64 -d > $HOME/.kube/config
    - kubectl config get-contexts
    #Fanart
    - kubectl --record deployment.apps/twitter-fanart set image deployment.v1.apps/twitter-fanart twitter=registry.gitlab.com/justhumanz/go-simp/fanart-twitter:"$CI_COMMIT_TAG"
    - kubectl --record deployment.apps/bilibili-fanart set image deployment.v1.apps/bilibili-fanart bilibili=registry.gitlab.com/justhumanz/go-simp/fanart-bilibili:"$CI_COMMIT_TAG"
    - kubectl --record deployment.apps/pixiv-fanart set image deployment.v1.apps/pixiv-fanart pixiv=registry.gitlab.com/justhumanz/go-simp/fanart-pixiv:"$CI_COMMIT_TAG"
    #Live
    - kubectl --record deployment.apps/bilibili-live set image deployment.v1.apps/bilibili-live livebili=registry.gitlab.com/justhumanz/go-simp/livebili-livestream:"$CI_COMMIT_TAG"
    - kubectl --record deployment.apps/bilibili-space set image deployment.v1.apps/bilibili-space spacebili=registry.gitlab.com/justhumanz/go-simp/spacebili-livestream:"$CI_COMMIT_TAG"    
    - kubectl --record deployment.apps/live-youtube set image deployment.v1.apps/live-youtube youtube=registry.gitlab.com/justhumanz/go-simp/youtube-livestream:"$CI_COMMIT_TAG"        
    - kubectl --record deployment.apps/twitch-youtube set image deployment.v1.apps/twitch-youtube twitch=registry.gitlab.com/justhumanz/go-simp/twitch-livestream:"$CI_COMMIT_TAG"            

    - kubectl --record deployment.apps/go-simp-pilot set image deployment.v1.apps/go-simp-pilot pilot=registry.gitlab.com/justhumanz/go-simp/pilot:"$CI_COMMIT_TAG"
    - kubectl --record deployment.apps/go-simp-subscriber set image deployment.v1.apps/go-simp-subscriber subscriber=registry.gitlab.com/justhumanz/go-simp/subscriber:"$CI_COMMIT_TAG"
    - kubectl --record deployment.apps/go-simp-utility set image deployment.v1.apps/go-simp-utility utility=registry.gitlab.com/justhumanz/go-simp/utility:"$CI_COMMIT_TAG"
    - kubectl set env deployment/go-simp-frontend VERSION="$CI_COMMIT_TAG"
    - kubectl --record deployment.apps/go-simp-frontend set image deployment.v1.apps/go-simp-frontend frontend=registry.gitlab.com/justhumanz/go-simp/frontend:"$CI_COMMIT_TAG"    
    - kubectl rollout restart deployment.apps/go-simp-web
  tags:
    - k8s    
  when: manual  
