version: "3.7"

services:
  build_mainbot:
    build: .
    image: mainbot
  
  build_go_simp_web:
    build: service/Go-Simp-Web
    image: go_simp_web
    
  build_rest_api:
    build: service/rest-api
    image: rest_api

  build_multitor:
    build: service/multitor
    image: tor_go_brrrrrrr

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1sampai8
      MYSQL_DATABASE: Vtuber
      MYSQL_USER: vtuber
      MYSQL_PASSWORD: kano2525
    restart: on-failure
    command: mysqld --sql_mode=""

  multi_tor:
    image: tor_go_brrrrrrr
    environment: 
    - TOR_INSTANCES=20

  db_migrate:
    image: mainbot
    depends_on:
      - mysql  
      - build_mainbot
    working_dir: /app/Go-Simp/service/db
    command: go run .
    restart: on-failure    

  backend:
    image: mainbot
    depends_on:
      - mysql
      - db_migrate
      - multi_tor
      - build_mainbot
    working_dir: /app/Go-Simp/pkg/backend
    command: go run .
    restart: on-failure

  frontend:
    image: mainbot
    depends_on:
      - mysql
      - db_migrate
      - multi_tor
      - build_mainbot
    working_dir: /app/Go-Simp/pkg/frontend
    command: go run .
    restart: on-failure

  guild:
    image: mainbot
    depends_on:
      - mysql
      - db_migrate
      - multi_tor
      - build_mainbot
    working_dir: /app/Go-Simp/pkg/guild
    command: go run .
    restart: on-failure
    volumes:
      - guild-volume:/app/Go-Simp/pkg/guild/guild.db

  yotube-scrap:
    build: service/yt-scrap
    image: yt-scrap
    env_file:
      - ./.env

  rest_api:
    image: rest_api
    depends_on:
      - mysql
      - db_migrate
    env_file:
      - ./.env
    ports:
      - "1107:2525"
    restart: on-failure

  go_simp_web:
    image: go_simp_web
    env_file:
      - ./.env    
    depends_on:
    - rest_api
    ports:
    - "1337:8000"
    restart: on-failure    

volumes:
  guild-volume:
