version: "3.7"

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1sampai8
      MYSQL_DATABASE: Vtuber
      MYSQL_USER: vtuber
      MYSQL_PASSWORD: kano2525
    restart: on-failure

  multi_tor:
    image: evait/multitor
    environment: 
    - TOR_INSTANCES=20

  mainbot:
    build: .
    image: mainbot
    depends_on:
      - mysql
      - db_migrate
      - multi_tor
    restart: on-failure
    command: go run .

  db_migrate:
    image: mainbot
    depends_on:
      - mysql
    working_dir: /go/src/github.com/JustHumanz/Go-Simp/service/db
    command: go run .
    restart: on-failure    

  yotube-scrap:
    build: service/yt-scrap
    image: yt-scrap

    env_file:
      - ./.env

  rest_api:
    build: service/rest-api
    image: rest-api

    depends_on:
      - mysql
      - db_migrate
    env_file:
      - ./.env
    ports:
      - "1107:2525"
    restart: on-failure