version: "3.7"

services:
  build_go-simp:
    build: .
    image: go-simp

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1sampai8
      MYSQL_DATABASE: Vtuber
      MYSQL_USER: vtuber
      MYSQL_PASSWORD: kano2525
    restart: on-failure
    command: mysqld --sql_mode=""
    networks:
      - go_simp-net    

  multi_tor:
    build: service/multitor
    networks:
      - go_simp-net

  db_migrate:
    build: ./service/migrate
    depends_on:
      - mysql  

    command: ./start.sh
    restart: on-failure    
    networks:
      - go_simp-net

  bilibili-fanart:
    build: ./service/fanart/bilibili
    depends_on:
      - mysql
      - db_migrate
      - multi_tor

    restart: on-failure
    networks:
      - go_simp-net

  twitter-fanart:
    build: ./service/fanart/twitter
    depends_on:
      - mysql
      - db_migrate
      - multi_tor

    restart: on-failure
    networks:
      - go_simp-net

  pixiv-fanart:
    build: ./service/fanart/pixiv
    depends_on:
      - mysql
      - db_migrate
      - multi_tor

    restart: on-failure
    networks:
      - go_simp-net

  livestream-livebili:
    build: ./service/livestream/bilibili/live
    depends_on:
      - mysql
      - db_migrate
      - multi_tor

    restart: on-failure
    networks:
      - go_simp-net

  livestream-spacebili:
    build: ./service/livestream/bilibili/space
    depends_on:
      - mysql
      - db_migrate
      - multi_tor

    restart: on-failure
    networks:
      - go_simp-net

  livestream-youtube:
    build: ./service/livestream/youtube
    depends_on:
      - mysql
      - db_migrate
      - multi_tor

    restart: on-failure
    networks:
      - go_simp-net

  livestream-twitch:
    build: ./service/livestream/twitch
    depends_on:
      - mysql
      - db_migrate
      - multi_tor

    restart: on-failure
    networks:
      - go_simp-net

  subscriber:
    build: ./service/subscriber/
    depends_on:
      - mysql
      - db_migrate
      - multi_tor

    restart: on-failure    
    networks:
      - go_simp-net

  utility:
    build: ./service/utility/
    depends_on:
      - mysql
      - db_migrate
      - multi_tor

    command: go run .
    restart: on-failure    
    networks:
      - go_simp-net

  frontend:
    build: ./service/frontend/
    depends_on:
      - mysql
      - db_migrate
      - multi_tor

    restart: on-failure
    networks:
      - go_simp-net

  guild:
    build: ./service/guild/
    depends_on:
      - mysql
      - db_migrate
      - multi_tor

    restart: on-failure
    networks:
      - go_simp-net

  pilot:
    build: ./service/pilot/
    depends_on:
      - mysql
      - db_migrate
      - multi_tor

    restart: on-failure
    volumes:
      - ./config.toml:/app/Go-Simp/config.toml    
    networks:
      - go_simp-net      

#  yotube-scrap:
#    build: service/yt-scrap
#    image: yt-scrap
#    env_file:
#      - ./.env
#    networks:
#      - go_simp-net         

  traefik:
    image: traefik:2.3
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./traefik.yml:/traefik.yml
      - ./acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock

  static_files:
    build: ./Img/
    networks:
      - go_simp-proxy
    labels:
      - traefik.http.routers.static-http.rule=Host(`<YOUR_DOMAIN>`)
      - traefik.http.routers.static-http.entrypoints=http
      - traefik.http.routers.static-http.middlewares=redirect
      - traefik.http.routers.static-https.rule=Host(`<YOUR_DOMAIN>`)
      - traefik.http.routers.static-https.entrypoints=https
      - traefik.http.routers.static-https.tls=true
      - traefik.http.routers.static-https.tls.certresolver=letsencrypt
      - traefik.http.services.static-service.loadbalancer.server.port=80
      - traefik.http.middlewares.redirect.redirectscheme.scheme=https

  go_simp_web:
    build: service/web
    env_file:
      - ./.env    
    depends_on:
    - rest_api
    restart: on-failure    
    networks:
      - go_simp-proxy
    labels:
      # Traefik configuration, Hostname needs to be changed
      - traefik.http.routers.go_simp_web-http.rule=Host(`<YOUR_DOMAIN>`)
      - traefik.http.routers.go_simp_web-http.entrypoints=http
      - traefik.http.routers.go_simp_web-http.middlewares=redirect
      - traefik.http.routers.go_simp_web-https.rule=Host(`<YOUR_DOMAIN>`)
      - traefik.http.routers.go_simp_web-https.entrypoints=https
      - traefik.http.routers.go_simp_web-https.tls=true
      - traefik.http.routers.go_simp_web-https.tls.certresolver=letsencrypt
      - traefik.http.services.go_simp_web.loadbalancer.server.port=8000
      - traefik.http.middlewares.redirect.redirectscheme.scheme=https

  rest_api:
    build: service/rest-api
    image: build_go-simp_rest-api
    working_dir: /app/Go-Simp/service/rest-api    
    depends_on:

      - redis
    command: go run . 
    restart: on-failure
    ports:
      - "2525:2525"    
    networks:
      - go_simp-proxy
      - go_simp-net
    labels:
      # Traefik configuration, Hostname needs to be changed
      - traefik.http.routers.rest_api-http.rule=Host(`<YOUR_DOMAIN>`)
      - traefik.http.routers.rest_api-http.entrypoints=http
      - traefik.http.routers.rest_api-http.middlewares=redirect
      - traefik.http.routers.rest_api-https.rule=Host(`<YOUR_DOMAIN>`)
      - traefik.http.routers.rest_api-https.entrypoints=https
      - traefik.http.routers.rest_api-https.tls=true
      - traefik.http.routers.rest_api-https.tls.certresolver=letsencrypt
      - traefik.http.services.rest_api.loadbalancer.server.port=2525
      - traefik.http.middlewares.redirect.redirectscheme.scheme=https

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:  
      - redis_data:/bitnami/redis/data/
    networks:
      - go_simp-net

  prometheus:
    image: prom/prometheus
    ports:
      - "8080:8080"        
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/etc/prometheus
    networks:
      - go_simp-proxy
      - go_simp-net      
networks:
  go_simp-proxy:
    external: true
  go_simp-net:
    external: false

volumes:
  redis_data:
  prometheus_data: