version: "3.7"

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1sampai8
      MYSQL_DATABASE: Vtuber
      MYSQL_USER: vtuber
      MYSQL_PASSWORD: kano2525
    restart: on-failure
    command: mysqld --sql_mode=""
    networks:
      - go_simp-net    

  multi_tor:
    build: service/multitor
    image: go-simp-multi_tor
    networks:
      - go_simp-net

  db_migrate:
    build: ./service/migrate
    image: go-simp-db_migrate
    depends_on:
      - mysql  
    restart: on-failure    
    networks:
      - go_simp-net

  bilibili-fanart:
    build: ./service/fanart/bilibili
    image: go-simp-bilibili-fanart
    depends_on:
      - mysql
      - db_migrate
      - multi_tor
    restart: on-failure
    networks:
      - go_simp-net

  twitter-fanart:
    build: ./service/fanart/twitter
    image: go-simp-twitter-fanart
    depends_on:
      - mysql
      - db_migrate
      - multi_tor
    restart: on-failure
    networks:
      - go_simp-net

  pixiv-fanart:
    build: ./service/fanart/pixiv
    image: go-simp-pixiv-fanart
    depends_on:
      - mysql
      - db_migrate
      - multi_tor
    restart: on-failure
    networks:
      - go_simp-net

  livestream-livebili:
    build: ./service/livestream/bilibili/live
    image: go-simp-livestream-livebili
    depends_on:
      - mysql
      - db_migrate
      - multi_tor
    restart: on-failure
    networks:
      - go_simp-net

  livestream-spacebili:
    build: ./service/livestream/bilibili/space
    image: go-simp-livestream-spacebili
    depends_on:
      - mysql
      - db_migrate
      - multi_tor
    restart: on-failure
    networks:
      - go_simp-net

  livestream-youtube:
    build: ./service/livestream/youtube
    image: go-simp-livestream-youtube
    depends_on:
      - mysql
      - db_migrate
      - multi_tor
    restart: on-failure
    networks:
      - go_simp-net

  livestream-twitch:
    build: ./service/livestream/twitch
    image: go-simp-livestream-twitch
    depends_on:
      - mysql
      - db_migrate
      - multi_tor
    restart: on-failure
    networks:
      - go_simp-net

  subscriber:
    build: ./service/subscriber/
    image: go-simp-subscriber
    depends_on:
      - mysql
      - db_migrate
      - multi_tor
    restart: on-failure    
    networks:
      - go_simp-net

  utility:
    build: ./service/utility/
    image: go-simp-utility
    depends_on:
      - mysql
      - db_migrate
      - multi_tor
    command: go run .
    restart: on-failure    
    networks:
      - go_simp-net

  frontend:
    build: ./service/frontend/
    image: go-simp-frontend
    depends_on:
      - mysql
      - db_migrate
      - multi_tor
    restart: on-failure
    networks:
      - go_simp-net

  guild:
    build: ./service/guild/
    image: go-simp-guild    
    depends_on:
      - mysql
      - db_migrate
      - multi_tor
    restart: on-failure
    networks:
      - go_simp-net

  pilot:
    build: ./service/pilot/
    image: go-simp-pilot
    depends_on:
      - mysql
      - db_migrate
      - multi_tor
    restart: on-failure
    volumes:
      - ./config.toml:/app/Go-Simp/config.toml    
    networks:
      - go_simp-net      

#  yotube-scrap:
#    build: service/yt-scrap
#    image: yt-scrap
#    env_file:
#      - ./.env
#    networks:
#      - go_simp-net         

  static_files:
    build: ./Img/
    networks:
      - go_simp-proxy

  go_simp_web:
    build: service/web-vue
    image: go-simp-web
    env_file:
      - ./.env    
    depends_on:
    - rest_api
    restart: on-failure    
    networks:
      - go_simp-proxy

  rest_api:
    build: service/rest-api
    image: go-simp-api
    working_dir: /app/Go-Simp/service/rest-api    
    depends_on:
      - redis
    command: go run . 
    restart: on-failure
    ports:
      - "2525:2525"    
    networks:
      - go_simp-proxy
      - go_simp-net

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:  
      - redis_data:/bitnami/redis/data/
    networks:
      - go_simp-net

  go_simp_prediction:
    build: service/prediction
    image: go-simp-prediction
    environment:
      - PrometheusURL=https://prometheus.humanz.moe
    restart: on-failure    
    networks:
      - go_simp-proxy

  prometheus:
    image: prom/prometheus
    ports:
      - "8080:8080"        
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/etc/prometheus
    networks:
      - go_simp-proxy
      - go_simp-net      
networks:
  go_simp-proxy:
    external: true
  go_simp-net:
    external: false

volumes:
  redis_data:
  prometheus_data: