FROM python:alpine

RUN apk add --update --no-cache
RUN mkdir /app
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
RUN pip install gunicorn
WORKDIR /app/Go_simpsPy

EXPOSE 8000
CMD ["gunicorn", "Go_simpsPy.wsgi:application", "--bind", "0.0.0.0:8000"]