FROM python:alpine

RUN apk add --update --no-cache git
RUN mkdir /app
WORKDIR /app
RUN git clone --single-branch --branch main https://github.com/JustHumanz/Go-Simp
RUN git checkout main
WORKDIR Go-Simp/service/Go-Simp-Web/
RUN pip install -r requirements.txt
RUN pip install gunicorn PyGithub
WORKDIR Go_simpsPy/

EXPOSE 8000
CMD ["gunicorn", "Go_simpsPy.wsgi:application", "--bind", "0.0.0.0:8000"]