// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pilot

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PilotServiceClient is the client API for PilotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PilotServiceClient interface {
	ReqData(ctx context.Context, in *ServiceMessage, opts ...grpc.CallOption) (*VtubersData, error)
	ModuleList(ctx context.Context, in *ModuleData, opts ...grpc.CallOption) (*Empty, error)
	RunModuleJob(ctx context.Context, in *ServiceMessage, opts ...grpc.CallOption) (*RunJob, error)
	HeartBeat(ctx context.Context, in *ServiceMessage, opts ...grpc.CallOption) (PilotService_HeartBeatClient, error)
	MetricReport(ctx context.Context, in *Metric, opts ...grpc.CallOption) (*Empty, error)
	ReportError(ctx context.Context, in *ServiceMessage, opts ...grpc.CallOption) (*Empty, error)
}

type pilotServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPilotServiceClient(cc grpc.ClientConnInterface) PilotServiceClient {
	return &pilotServiceClient{cc}
}

func (c *pilotServiceClient) ReqData(ctx context.Context, in *ServiceMessage, opts ...grpc.CallOption) (*VtubersData, error) {
	out := new(VtubersData)
	err := c.cc.Invoke(ctx, "/pilot.PilotService/ReqData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pilotServiceClient) ModuleList(ctx context.Context, in *ModuleData, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pilot.PilotService/ModuleList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pilotServiceClient) RunModuleJob(ctx context.Context, in *ServiceMessage, opts ...grpc.CallOption) (*RunJob, error) {
	out := new(RunJob)
	err := c.cc.Invoke(ctx, "/pilot.PilotService/RunModuleJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pilotServiceClient) HeartBeat(ctx context.Context, in *ServiceMessage, opts ...grpc.CallOption) (PilotService_HeartBeatClient, error) {
	stream, err := c.cc.NewStream(ctx, &PilotService_ServiceDesc.Streams[0], "/pilot.PilotService/HeartBeat", opts...)
	if err != nil {
		return nil, err
	}
	x := &pilotServiceHeartBeatClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PilotService_HeartBeatClient interface {
	Recv() (*Empty, error)
	grpc.ClientStream
}

type pilotServiceHeartBeatClient struct {
	grpc.ClientStream
}

func (x *pilotServiceHeartBeatClient) Recv() (*Empty, error) {
	m := new(Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pilotServiceClient) MetricReport(ctx context.Context, in *Metric, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pilot.PilotService/MetricReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pilotServiceClient) ReportError(ctx context.Context, in *ServiceMessage, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pilot.PilotService/ReportError", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PilotServiceServer is the server API for PilotService service.
// All implementations must embed UnimplementedPilotServiceServer
// for forward compatibility
type PilotServiceServer interface {
	ReqData(context.Context, *ServiceMessage) (*VtubersData, error)
	ModuleList(context.Context, *ModuleData) (*Empty, error)
	RunModuleJob(context.Context, *ServiceMessage) (*RunJob, error)
	HeartBeat(*ServiceMessage, PilotService_HeartBeatServer) error
	MetricReport(context.Context, *Metric) (*Empty, error)
	ReportError(context.Context, *ServiceMessage) (*Empty, error)
	mustEmbedUnimplementedPilotServiceServer()
}

// UnimplementedPilotServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPilotServiceServer struct {
}

func (UnimplementedPilotServiceServer) ReqData(context.Context, *ServiceMessage) (*VtubersData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReqData not implemented")
}
func (UnimplementedPilotServiceServer) ModuleList(context.Context, *ModuleData) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModuleList not implemented")
}
func (UnimplementedPilotServiceServer) RunModuleJob(context.Context, *ServiceMessage) (*RunJob, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunModuleJob not implemented")
}
func (UnimplementedPilotServiceServer) HeartBeat(*ServiceMessage, PilotService_HeartBeatServer) error {
	return status.Errorf(codes.Unimplemented, "method HeartBeat not implemented")
}
func (UnimplementedPilotServiceServer) MetricReport(context.Context, *Metric) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MetricReport not implemented")
}
func (UnimplementedPilotServiceServer) ReportError(context.Context, *ServiceMessage) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportError not implemented")
}
func (UnimplementedPilotServiceServer) mustEmbedUnimplementedPilotServiceServer() {}

// UnsafePilotServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PilotServiceServer will
// result in compilation errors.
type UnsafePilotServiceServer interface {
	mustEmbedUnimplementedPilotServiceServer()
}

func RegisterPilotServiceServer(s grpc.ServiceRegistrar, srv PilotServiceServer) {
	s.RegisterService(&PilotService_ServiceDesc, srv)
}

func _PilotService_ReqData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PilotServiceServer).ReqData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pilot.PilotService/ReqData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PilotServiceServer).ReqData(ctx, req.(*ServiceMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _PilotService_ModuleList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModuleData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PilotServiceServer).ModuleList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pilot.PilotService/ModuleList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PilotServiceServer).ModuleList(ctx, req.(*ModuleData))
	}
	return interceptor(ctx, in, info, handler)
}

func _PilotService_RunModuleJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PilotServiceServer).RunModuleJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pilot.PilotService/RunModuleJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PilotServiceServer).RunModuleJob(ctx, req.(*ServiceMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _PilotService_HeartBeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ServiceMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PilotServiceServer).HeartBeat(m, &pilotServiceHeartBeatServer{stream})
}

type PilotService_HeartBeatServer interface {
	Send(*Empty) error
	grpc.ServerStream
}

type pilotServiceHeartBeatServer struct {
	grpc.ServerStream
}

func (x *pilotServiceHeartBeatServer) Send(m *Empty) error {
	return x.ServerStream.SendMsg(m)
}

func _PilotService_MetricReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Metric)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PilotServiceServer).MetricReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pilot.PilotService/MetricReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PilotServiceServer).MetricReport(ctx, req.(*Metric))
	}
	return interceptor(ctx, in, info, handler)
}

func _PilotService_ReportError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PilotServiceServer).ReportError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pilot.PilotService/ReportError",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PilotServiceServer).ReportError(ctx, req.(*ServiceMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// PilotService_ServiceDesc is the grpc.ServiceDesc for PilotService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PilotService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pilot.PilotService",
	HandlerType: (*PilotServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReqData",
			Handler:    _PilotService_ReqData_Handler,
		},
		{
			MethodName: "ModuleList",
			Handler:    _PilotService_ModuleList_Handler,
		},
		{
			MethodName: "RunModuleJob",
			Handler:    _PilotService_RunModuleJob_Handler,
		},
		{
			MethodName: "MetricReport",
			Handler:    _PilotService_MetricReport_Handler,
		},
		{
			MethodName: "ReportError",
			Handler:    _PilotService_ReportError_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HeartBeat",
			Handler:       _PilotService_HeartBeat_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grpc.proto",
}
