// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.7
// source: grpc.proto

package pilot

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VtubersData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VtuberPayload []byte `protobuf:"bytes,1,opt,name=VtuberPayload,proto3" json:"VtuberPayload,omitempty"`
	ConfigFile    []byte `protobuf:"bytes,2,opt,name=ConfigFile,proto3" json:"ConfigFile,omitempty"`
	WaitMigrate   bool   `protobuf:"varint,3,opt,name=WaitMigrate,proto3" json:"WaitMigrate,omitempty"`
}

func (x *VtubersData) Reset() {
	*x = VtubersData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VtubersData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VtubersData) ProtoMessage() {}

func (x *VtubersData) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VtubersData.ProtoReflect.Descriptor instead.
func (*VtubersData) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *VtubersData) GetVtuberPayload() []byte {
	if x != nil {
		return x.VtuberPayload
	}
	return nil
}

func (x *VtubersData) GetConfigFile() []byte {
	if x != nil {
		return x.ConfigFile
	}
	return nil
}

func (x *VtubersData) GetWaitMigrate() bool {
	if x != nil {
		return x.WaitMigrate
	}
	return false
}

type ServiceMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	Service string `protobuf:"bytes,2,opt,name=Service,proto3" json:"Service,omitempty"`
	Alive   bool   `protobuf:"varint,3,opt,name=Alive,proto3" json:"Alive,omitempty"`
}

func (x *ServiceMessage) Reset() {
	*x = ServiceMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceMessage) ProtoMessage() {}

func (x *ServiceMessage) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceMessage.ProtoReflect.Descriptor instead.
func (*ServiceMessage) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ServiceMessage) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ServiceMessage) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

type ModuleData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Module  string `protobuf:"bytes,1,opt,name=Module,proto3" json:"Module,omitempty"`
	Enabled bool   `protobuf:"varint,2,opt,name=Enabled,proto3" json:"Enabled,omitempty"`
}

func (x *ModuleData) Reset() {
	*x = ModuleData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleData) ProtoMessage() {}

func (x *ModuleData) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleData.ProtoReflect.Descriptor instead.
func (*ModuleData) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *ModuleData) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *ModuleData) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type Metric struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MetricData []byte `protobuf:"bytes,1,opt,name=MetricData,proto3" json:"MetricData,omitempty"`
	State      string `protobuf:"bytes,2,opt,name=State,proto3" json:"State,omitempty"`
}

func (x *Metric) Reset() {
	*x = Metric{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *Metric) GetMetricData() []byte {
	if x != nil {
		return x.MetricData
	}
	return nil
}

func (x *Metric) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{4}
}

var File_grpc_proto protoreflect.FileDescriptor

var file_grpc_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x69,
	0x6c, 0x6f, 0x74, 0x22, 0x75, 0x0a, 0x0b, 0x56, 0x74, 0x75, 0x62, 0x65, 0x72, 0x73, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x24, 0x0a, 0x0d, 0x56, 0x74, 0x75, 0x62, 0x65, 0x72, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x56, 0x74, 0x75, 0x62, 0x65,
	0x72, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x57, 0x61, 0x69, 0x74,
	0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x57,
	0x61, 0x69, 0x74, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x22, 0x5a, 0x0a, 0x0e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x05, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x22, 0x3e, 0x0a, 0x0a, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x45,
	0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x22, 0x3e, 0x0a, 0x06, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x12, 0x1e, 0x0a, 0x0a, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32,
	0xdc, 0x01, 0x0a, 0x0c, 0x50, 0x69, 0x6c, 0x6f, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x36, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x44, 0x61, 0x74, 0x61, 0x12, 0x15, 0x2e, 0x70, 0x69,
	0x6c, 0x6f, 0x74, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x1a, 0x12, 0x2e, 0x70, 0x69, 0x6c, 0x6f, 0x74, 0x2e, 0x56, 0x74, 0x75, 0x62, 0x65,
	0x72, 0x73, 0x44, 0x61, 0x74, 0x61, 0x22, 0x00, 0x12, 0x2f, 0x0a, 0x0a, 0x4d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x11, 0x2e, 0x70, 0x69, 0x6c, 0x6f, 0x74, 0x2e, 0x4d,
	0x6f, 0x64, 0x75, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x0c, 0x2e, 0x70, 0x69, 0x6c, 0x6f,
	0x74, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x09, 0x48, 0x65, 0x61,
	0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x12, 0x15, 0x2e, 0x70, 0x69, 0x6c, 0x6f, 0x74, 0x2e, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0c, 0x2e,
	0x70, 0x69, 0x6c, 0x6f, 0x74, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x30, 0x01, 0x12,
	0x2d, 0x0a, 0x0c, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12,
	0x0d, 0x2e, 0x70, 0x69, 0x6c, 0x6f, 0x74, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x1a, 0x0c,
	0x2e, 0x70, 0x69, 0x6c, 0x6f, 0x74, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x25,
	0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x75, 0x73,
	0x74, 0x68, 0x75, 0x6d, 0x61, 0x6e, 0x7a, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x70, 0x69, 0x6c, 0x6f, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_proto_rawDescOnce sync.Once
	file_grpc_proto_rawDescData = file_grpc_proto_rawDesc
)

func file_grpc_proto_rawDescGZIP() []byte {
	file_grpc_proto_rawDescOnce.Do(func() {
		file_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_proto_rawDescData)
	})
	return file_grpc_proto_rawDescData
}

var file_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_grpc_proto_goTypes = []interface{}{
	(*VtubersData)(nil),    // 0: pilot.VtubersData
	(*ServiceMessage)(nil), // 1: pilot.ServiceMessage
	(*ModuleData)(nil),     // 2: pilot.ModuleData
	(*Metric)(nil),         // 3: pilot.Metric
	(*Empty)(nil),          // 4: pilot.Empty
}
var file_grpc_proto_depIdxs = []int32{
	1, // 0: pilot.PilotService.ReqData:input_type -> pilot.ServiceMessage
	2, // 1: pilot.PilotService.ModuleList:input_type -> pilot.ModuleData
	1, // 2: pilot.PilotService.HeartBeat:input_type -> pilot.ServiceMessage
	3, // 3: pilot.PilotService.MetricReport:input_type -> pilot.Metric
	0, // 4: pilot.PilotService.ReqData:output_type -> pilot.VtubersData
	4, // 5: pilot.PilotService.ModuleList:output_type -> pilot.Empty
	4, // 6: pilot.PilotService.HeartBeat:output_type -> pilot.Empty
	4, // 7: pilot.PilotService.MetricReport:output_type -> pilot.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_proto_init() }
func file_grpc_proto_init() {
	if File_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VtubersData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModuleData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Metric); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_proto_goTypes,
		DependencyIndexes: file_grpc_proto_depIdxs,
		MessageInfos:      file_grpc_proto_msgTypes,
	}.Build()
	File_grpc_proto = out.File
	file_grpc_proto_rawDesc = nil
	file_grpc_proto_goTypes = nil
	file_grpc_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PilotServiceClient is the client API for PilotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PilotServiceClient interface {
	ReqData(ctx context.Context, in *ServiceMessage, opts ...grpc.CallOption) (*VtubersData, error)
	ModuleList(ctx context.Context, in *ModuleData, opts ...grpc.CallOption) (*Empty, error)
	HeartBeat(ctx context.Context, in *ServiceMessage, opts ...grpc.CallOption) (PilotService_HeartBeatClient, error)
	MetricReport(ctx context.Context, in *Metric, opts ...grpc.CallOption) (*Empty, error)
}

type pilotServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPilotServiceClient(cc grpc.ClientConnInterface) PilotServiceClient {
	return &pilotServiceClient{cc}
}

func (c *pilotServiceClient) ReqData(ctx context.Context, in *ServiceMessage, opts ...grpc.CallOption) (*VtubersData, error) {
	out := new(VtubersData)
	err := c.cc.Invoke(ctx, "/pilot.PilotService/ReqData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pilotServiceClient) ModuleList(ctx context.Context, in *ModuleData, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pilot.PilotService/ModuleList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pilotServiceClient) HeartBeat(ctx context.Context, in *ServiceMessage, opts ...grpc.CallOption) (PilotService_HeartBeatClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PilotService_serviceDesc.Streams[0], "/pilot.PilotService/HeartBeat", opts...)
	if err != nil {
		return nil, err
	}
	x := &pilotServiceHeartBeatClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PilotService_HeartBeatClient interface {
	Recv() (*Empty, error)
	grpc.ClientStream
}

type pilotServiceHeartBeatClient struct {
	grpc.ClientStream
}

func (x *pilotServiceHeartBeatClient) Recv() (*Empty, error) {
	m := new(Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pilotServiceClient) MetricReport(ctx context.Context, in *Metric, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pilot.PilotService/MetricReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PilotServiceServer is the server API for PilotService service.
type PilotServiceServer interface {
	ReqData(context.Context, *ServiceMessage) (*VtubersData, error)
	ModuleList(context.Context, *ModuleData) (*Empty, error)
	HeartBeat(*ServiceMessage, PilotService_HeartBeatServer) error
	MetricReport(context.Context, *Metric) (*Empty, error)
}

// UnimplementedPilotServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPilotServiceServer struct {
}

func (*UnimplementedPilotServiceServer) ReqData(context.Context, *ServiceMessage) (*VtubersData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReqData not implemented")
}
func (*UnimplementedPilotServiceServer) ModuleList(context.Context, *ModuleData) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModuleList not implemented")
}
func (*UnimplementedPilotServiceServer) HeartBeat(*ServiceMessage, PilotService_HeartBeatServer) error {
	return status.Errorf(codes.Unimplemented, "method HeartBeat not implemented")
}
func (*UnimplementedPilotServiceServer) MetricReport(context.Context, *Metric) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MetricReport not implemented")
}

func RegisterPilotServiceServer(s *grpc.Server, srv PilotServiceServer) {
	s.RegisterService(&_PilotService_serviceDesc, srv)
}

func _PilotService_ReqData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PilotServiceServer).ReqData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pilot.PilotService/ReqData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PilotServiceServer).ReqData(ctx, req.(*ServiceMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _PilotService_ModuleList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModuleData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PilotServiceServer).ModuleList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pilot.PilotService/ModuleList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PilotServiceServer).ModuleList(ctx, req.(*ModuleData))
	}
	return interceptor(ctx, in, info, handler)
}

func _PilotService_HeartBeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ServiceMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PilotServiceServer).HeartBeat(m, &pilotServiceHeartBeatServer{stream})
}

type PilotService_HeartBeatServer interface {
	Send(*Empty) error
	grpc.ServerStream
}

type pilotServiceHeartBeatServer struct {
	grpc.ServerStream
}

func (x *pilotServiceHeartBeatServer) Send(m *Empty) error {
	return x.ServerStream.SendMsg(m)
}

func _PilotService_MetricReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Metric)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PilotServiceServer).MetricReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pilot.PilotService/MetricReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PilotServiceServer).MetricReport(ctx, req.(*Metric))
	}
	return interceptor(ctx, in, info, handler)
}

var _PilotService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pilot.PilotService",
	HandlerType: (*PilotServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReqData",
			Handler:    _PilotService_ReqData_Handler,
		},
		{
			MethodName: "ModuleList",
			Handler:    _PilotService_ModuleList_Handler,
		},
		{
			MethodName: "MetricReport",
			Handler:    _PilotService_MetricReport_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HeartBeat",
			Handler:       _PilotService_HeartBeat_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grpc.proto",
}
