version: "3.7"

networks:
  go-simp-net:
    external: true

services:
  spacebili:
    image: justhumanz/go-simp-bilispace-livestream:${RELEASE_VERSION}
    depends_on:
      - multi_tor
    networks:
      - go-simp-net

  livebili:
    image: justhumanz/go-simp-bililive-livestream:${RELEASE_VERSION}
    depends_on:
      - multi_tor
    networks:
      - go-simp-net

  youtube:
    image: justhumanz/go-simp-youtube-checker-livestream:${RELEASE_VERSION}
    depends_on:
      - multi_tor
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - go-simp-net
    command: ./liveyoutube -MultiTOR  

  youtube_counter:
    image: justhumanz/go-simp-youtube-counter-livestream:${RELEASE_VERSION}
    depends_on:
      - multi_tor
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - go-simp-net

  twitch:
    image: justhumanz/go-simp-twitch-livestream:${RELEASE_VERSION}
    depends_on:
      - multi_tor
    networks:
      - go-simp-net