version: "3.7"

networks:
  go-simp-net:
    external: true

volumes:
  redis_data:
  prometheus_data:

services:
  multi_tor:
    image: evait/multitor
    deploy:
      replicas: 3    
    build: service/multitor
    networks:
      - go-simp-net

#  db_migrate:
#    build: ./service/migrate
#    volumes:
#      - ./service/migrate/vtuber.json:/vtuber.json
#    environment:
#      - PROMETHEUS="http://prometheus:9090"
#    restart: on-failure
#    networks:
#      - go-simp-net

  subscriber:
    image: subscriber
    build: ./service/subscriber/
    depends_on:
      - multi_tor
    restart: on-failure
    environment:
      - PrometheusURL=https://prometheus.humanz.moe
    networks:
      - go-simp-net

  utility:
    image: utility
    build: ./service/utility/
    depends_on:
      - multi_tor
    restart: on-failure
    environment:
      - TOPGG=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjcyMTk2NDUxNDAxODU5MDgwMiIsImJvdCI6dHJ1ZSwiaWF0IjoxNjEwMTI1Njk4fQ.o-nxrmws--nUdz7jh61bBTQ5dwUo0-4uZIQD_1L8Rac
    networks:
      - go-simp-net

  frontend:
    image: frontend
    build: ./service/frontend/
    depends_on:
      - multi_tor
    restart: on-failure
    environment:
      - PrometheusURL=https://prometheus.humanz.moe
    networks:
      - go-simp-net

  guild:
    image: guild
    build: ./service/guild/
    depends_on:
      - multi_tor
      - pilot
    restart: on-failure
    networks:
      - go-simp-net

  pilot:
    image: pilot
    build: ./service/pilot/
    depends_on:
      - multi_tor
    restart: on-failure
    volumes:
      - ../config.toml:/config.toml
    networks:
     - go-simp-net

#  yotube-scrap:
#    build: service/yt-scrap
#    image: yt-scrap
#    env_file:
#      - ./.env
#    networks:
#      - go-simp-net


  static_files:
    image: static_files
    build: ./Img/
    networks:
     - go-simp-net    
    ports:
      - "9191:80"

#  web-vue:
#    image: web-vue
#    build: service/web-vue
#    deploy:
#      replicas: 2
#    environment:
#      - RESTAPI=https://api.humanz.moe/
#    depends_on:
#    - rest_api
#    restart: on-failure
#    networks:
#      - go-simp-net
#    ports:
#      - "9292:80"

#  rest_api:
#    image: rest_api
#    build: service/rest-api
#    restart: on-failure
#    networks:
#      - go-simp-net
#    ports:
#      - "9393:2525"

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: on-failure
    volumes:
      - redis_data:/bitnami/redis/data/
    networks:
      - go-simp-net


  prediction:
    build: service/prediction
    image: prediction
    environment:
      - PrometheusURL=http://prometheus:9090
    restart: on-failure
    networks:
      - go-simp-net

  prometheus:
    image: prom/prometheus
    ports:
      - "9494:9090"
    volumes:
      - ../prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/etc/prometheus
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - go-simp-net

  proxy:
    image: nginx:latest
    volumes:
      - ../rev_proxy/nginx.conf:/etc/nginx/conf.d/app.conf
      - ../rev_proxy/tls.crt:/etc/ssl/humanz/tls.crt
      - ../rev_proxy/tls.key:/etc/ssl/humanz/tls.key
    ports:
      - "80:80"
      - "443:443"
    networks:
      - go-simp-net

