version: "3.7"

networks:
  go-simp-net:
    external: true
volumes:
  redis-data:

services:
  mysql:
    image: mysql:latest
    command: --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT}' # TODO: Change this
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASS: '${MYSQL_PASS}'
    volumes:
    - ./mysql_data:/var/lib/mysql
    networks:
      - go-simp-net  
    ports:
      - 3306:3306  

  multi_tor:
    image: justhumanz/go-multitor
    command: ["./MultiTOR","-key","${KEY}"]   
#    ports:
#      - 8080:8080          
    networks:
      - go-simp-net

#  db_migrate:
#    build: ./service/migrate
#    image: db_migrate
#    volumes:
#      - ../service/migrate/vtuber.json:/vtuber.json
#    deploy:
#      placement:
#        constraints:
#          - node.hostname == humanz-master
#    environment:
#      - PROMETHEUS="http://prometheus:9090"
#    restart: on-failure
#    networks:
#      - go-simp-net

  pilot:
    image: justhumanz/go-simp-pilot:latest
    depends_on:
      - multi_tor
    volumes:
      - ../config.toml:/config.toml
    networks:
     - go-simp-net

  utility:                                                                                                                                                                                                           
    image: justhumanz/go-simp-utility                                                                                                                                                                                                   
    depends_on:                                                                                                                                                                                                      
      - multi_tor                                                                                                                                                                                                    
    environment:                                                                                                                                                                                                     
      - TOPGG=${TOPGG}                                            
    networks:                                                                                                                                                                                                        
      - go-simp-net

  static_files:
    image: nginx:alpine
    volumes:
      - ../Img/nginx.conf:/etc/nginx/nginx.conf
      - ../Img/:/usr/share/nginx/html
    networks:
     - go-simp-net    
    ports:
      - "9191:80"

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-data:/bitnami/redis/data/
    networks:
      - go-simp-net


  prometheus:
    image: bitnami/prometheus:latest
    ports:
      - "9494:9090"
    volumes:
      - ../prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
      - ./prometheus_data:/opt/bitnami/prometheus/data
      - "/etc/localtime:/etc/localtime:ro"
    command: ["--config.file=/etc/prometheus/prometheus.yml","--storage.tsdb.path=/prometheus","--web.console.libraries=/usr/share/prometheus/console_libraries","--web.console.templates=/usr/share/prometheus/consoles","--storage.tsdb.retention.time=365d"]
    networks:
      - go-simp-net

  proxy:
    image: nginx:alpine
    volumes:
      - ../rev_proxy/nginx.conf:/etc/nginx/conf.d/app.conf
      - ../rev_proxy/tls.crt:/etc/ssl/humanz/tls.crt
      - ../rev_proxy/tls.key:/etc/ssl/humanz/tls.key
    ports:
      - "80:80"
      - "443:443"
    networks:
      - go-simp-net
