version: "3.7"

networks:
  go-simp-net:
    external: true

services:

  db_migrate:
    image: justhumanz/go-simp-migrate
    volumes:
      - ../service/migrate/json:/json
    environment:
      - PROMETHEUS="http://prometheus:9090"
    networks:
      - go-simp-net