version: "3.7"                                                                                                                                                                                                       
                                                                                                                                                                                                                     
networks:                                                                                                                                                                                                            
  go-simp-net:                                                                                                                                                                                                       
    external: true                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                     
services:                                                                                                                                                                                                            
  subscriber_bilibili:                                                                                                                                                                                                        
    image: justhumanz/go-simp-subscriber-bilibili:${RELEASE_VERSION}                                                                                                                                                                                                
    depends_on:                                                                                                                                                                                                      
      - multi_tor                                                                                                                                                                                                    
    environment:                          
      - PrometheusURL=https://prometheus.humanz.moe  
    networks:                                      
      - go-simp-net    

  subscriber_twitch:                                                                                                                                                                                                        
    image: justhumanz/go-simp-subscriber-twitch:${RELEASE_VERSION}                                                                                                                                                                                                
    depends_on:                                                                                                                                                                                                      
      - multi_tor                                                                                                                                                                                                    
    environment:                          
      - PrometheusURL=https://prometheus.humanz.moe  
    networks:                                      
      - go-simp-net    

  subscriber_twitter:                                                                                                                                                                                                        
    image: justhumanz/go-simp-subscriber-twitter:${RELEASE_VERSION}                                                                                                                                                                                                
    depends_on:                                                                                                                                                                                                      
      - multi_tor                                                                                                                                                                                                    
    environment:                          
      - PrometheusURL=https://prometheus.humanz.moe  
    networks:                                      
      - go-simp-net    

  subscriber_youtube:
    image: justhumanz/go-simp-subscriber-youtube:${RELEASE_VERSION}                                                                                                                                                                                                
    depends_on:                                                                                                                                                                                                      
      - multi_tor                                                                                                                                                                                                    
    environment:                          
      - PrometheusURL=https://prometheus.humanz.moe  
    networks:                                      
      - go-simp-net    


  frontend:                                          
    image: justhumanz/go-simp-frontend:${RELEASE_VERSION}
    depends_on:                           
      - multi_tor                                    
    environment:                       
      - PrometheusURL=https://prometheus.humanz.moe  
    networks:                                        
      - go-simp-net                                  
                                                     
  web-vue:                                           
    image: justhumanz/go-simp-web-vue-v2:latest
    deploy:
      replicas: 2                                                         
    depends_on:                                                     
    - rest_api                                                                                       
    networks:                                                       
      - go-simp-net                                                            
    ports:                                                                     
      - "9292:80"                                                              
                             
  web-admin-api:                                           
    image: justhumanz/go-simp-web-admin-api:latest         
    environment:                                     
      - SECRET=${BOT_SECRET}
      - CLIENTID=${BOT_CLIENTID}
      - CALLBACK_URL=https://web-admin.humanz.moe/callback
      - URL=https://web-admin.humanz.moe
      - BOT=${BOT}
      - DB_PASS=${DB_PASS}
      - DB_USER=root
      - DB_HOST=mysql              
    networks:                                                       
      - go-simp-net

  web-admin-vue:                                           
    image: justhumanz/go-simp-web-admin-vue:latest
    networks:                                                       
      - go-simp-net                                                            
      
  rest_api:                                                                    
    image: justhumanz/go-simp-rest_api-v2:${RELEASE_VERSION}                                                                                                       
    networks:                                                                                  
      - go-simp-net                                                                                                                                                       