version: "3.7"                                                                                                                                                                                                       
                                                                                                                                                                                                                     
networks:                                                                                                                                                                                                            
  go-simp-net:                                                                                                                                                                                                       
    external: true                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                     
services:                                                                                                                                                                                                            
  subscriber:                                                                                                                                                                                                        
    image: justhumanz/go-simp-subscriber:${RELEASE_VERSION}                                                                                                                                                                                                
    depends_on:                                                                                                                                                                                                      
      - multi_tor                                                                                                                                                                                                    
    environment:                          
      - PrometheusURL=https://prometheus.humanz.moe  
    networks:                                      
      - go-simp-net    
                                                                                                                        
  frontend:                                          
    image: justhumanz/go-simp-frontend:${RELEASE_VERSION}                                  
    depends_on:                           
      - multi_tor                                    
    environment:                       
      - PrometheusURL=https://prometheus.humanz.moe  
    networks:                                        
      - go-simp-net                                  
                                                     
  web-vue:                                           
    image: justhumanz/go-simp-web-vue:${RELEASE_VERSION}                        
    environment:                                     
      - RESTAPI=https://api.humanz.moe/              
    deploy:
      replicas: 2                                                         
    depends_on:                                                     
    - rest_api                                                                                       
    networks:                                                       
      - go-simp-net                                                            
    ports:                                                                     
      - "9292:80"                                                              
                                                                    
  rest_api:                                                                    
    image: justhumanz/go-simp-rest_api:${RELEASE_VERSION}                                                                                                       
    networks:                                                                                  
      - go-simp-net                                                                            
    ports:                                                                                     
      - "9393:2525"                                                                            