apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-simp-fanart
  labels:           
    app: go-simp
    tier: backend
spec:
  selector:
    matchLabels:    
      app: fanart
      tier: backend
  template:         
    metadata:
      labels:       
        app: fanart
        tier: backend
    spec:
      containers:
        - name: go-simp-fanart
          image: justhumanz/go-simp
          #imagePullPolicy: IfNotPresent  
          workingDir: /app/Go-Simp/service/fanart/
          command: go build -o fanart && ./fanart -TwitterFanart -BiliBiliFanart                 
      restartPolicy: OnFailure