apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-simp-frontend
  labels:           
    app: go-simp
    tier: backend
spec:
  selector:
    matchLabels:    
      app: frontend
      tier: backend
  template:         
    metadata:
      labels:       
        app: frontend
        tier: backend
    spec:
      containers:
        - name: go-simp-frontend
          image: justhumanz/go-simp
          #imagePullPolicy: IfNotPresent  
          workingDir: /app/Go-Simp/service/frontend/
          command: go build -o frontend && ./frontend
      restartPolicy: OnFailure          