apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-simp-live
  labels:           
    app: go-simp
    tier: backend
spec:
  selector:
    matchLabels:    
      app: live
      tier: backend
  template:         
    metadata:
      labels:       
        app: live
        tier: backend
    spec:           
      containers:
        - name: go-simp-livestream
          image: go-simp_livestream
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: config-volume
            mountPath: /app/Go-Simp
      volumes:
        - name: config-volume
          configMap:
            name: Go-Simp_config_file          