apiVersion: v1
kind: Pod
metadata:
  name: migrate
spec:
  containers:
    - name: go-simp-migrate
      image: go-simp_db_migrate
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - name: config-volume
        mountPath: /app/Go-Simp
    volumes:
      - name: config-volume
        configMap:
          name: Go-Simp_config_file      
  restartPolicy: OnFailure    