apiVersion: v1
kind: Pod
metadata:
  name: migrate
spec:
  containers:
    - name: go-simp-migrate
      image: justhumanz/go-simp
      #imagePullPolicy: IfNotPresent  
      workingDir: /app/Go-Simp/service/migrate/
      command: go run .
  restartPolicy: OnFailure    