apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-simp-pilot
  labels:           
    app: go-simp
    tier: backend
spec:
  selector:
    matchLabels:    
      app: pilot
      tier: backend
  template:         
    metadata:
      labels:       
        app: pilot
        tier: backend
    spec:           
      containers:
        - name: go-simp-pilot
          image: justhumanz/go-simp
          #imagePullPolicy: IfNotPresent  
          volumeMounts:
          - name: config-volume
            mountPath: /app/Go-Simp/config.toml
          workingDir: /app/Go-Simp/service/pilot/
          command: ["./pilot"]
      volumes:
        - name: config-volume
          configMap:
            name: go-simp-configfile             
      restartPolicy: Always           