apiVersion: v1
kind: Service
metadata:
  name: rest-api
  labels:           
    app: rest-api
    tier: frontend
spec:
  ports:
  - name: rest-api
    port: 2525      
    targetPort: 2525
  selector:         
    app: rest-api
    tier: frontend
  type: LoadBalancer  

---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: rest-api
  labels:
    app: rest-api      
spec:
  selector:
    matchLabels:    
      app: rest-api
      tier: frontend
  replicas: 2       
  template:         
    metadata:
      labels:       
        app: rest-api
        tier: frontend
    spec:           
      containers:
      - name: rest-api
        image: justhumanz/go-simp
        #imagePullPolicy: IfNotPresent  
        workingDir: /app/Go-Simp/service/rest-api/
        command: go build -o api && ./api
      restartPolicy: OnFailure        