apiVersion: v1
kind: Service
metadata:
  name: rest-api
  labels:           
    app: rest-api
    tier: frontend
spec:
  ports:
  - name: rest-api
    port: 2525      
    targetPort: 2525
  selector:         
    app: rest-api
    tier: frontend
  type: LoadBalancer  

---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: rest-api
  labels:
    app: rest-api      
spec:
  selector:
    matchLabels:    
      app: rest-api
      tier: frontend
  replicas: 2       
  template:         
    metadata:
      labels:       
        app: rest-api
        tier: frontend
    spec:           
      containers:
      - name: rest-api
        image: mainbot_rest-api
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2525
        volumeMounts:
        - name: config-volume
          mountPath: /app/Go-Simp
          
      volumes:
        - name: config-volume
          configMap:
            name: Go-Simp_config_file        