FROM golang:alpine

RUN apk update && apk add mysql-client git bash
RUN go get -u github.com/JustHumanz/Go-Simp

RUN mkdir /apps/

COPY . /apps/
WORKDIR /apps/
#RUN chmod +x start.sh
#CMD ["./start.sh"]
#RUN chmod +x db.sh
CMD ["go","run","."]