name: build go-simp migrate module

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Hash
        id: hash
        run: echo "git_hash=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_HASH
                  
    ## Build main image
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: justhumanz/go-simp:{{ env.hash }}

    ### Migrate
      
      - name: Build and push migrate
        uses: docker/build-push-action@v2
        with:
          context: ./service/migrate/
          push: true
          tags: justhumanz/go-simp-migrate:latest       
          build-args: |
            BASE_IMAGE=justhumanz/go-simp:{{ env.hash }}              