name: build go-simp lts module

on:
  push:
    paths:
      - 'service/pilot/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    ### Pilot      
      -
        name: Build and push go-simp-pilot
        uses: docker/build-push-action@v2
        with:
          context: ./service/pilot
          push: true
          tags: justhumanz/go-simp-pilot:latest

    ### Guild
      -
        name: Build and push go-simp-guild
        uses: docker/build-push-action@v2
        with:
          context: ./service/guild
          push: true
          tags: justhumanz/go-simp-guild:latest

    ### Utility
      -
        name: Build and push go-simp-utility
        uses: docker/build-push-action@v2
        with:
          context: ./service/utility
          push: true
          tags: justhumanz/go-simp-utility:latest