name: build go-simp lts module

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
                  
    ## Build main image
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: justhumanz/go-simp:${{ github.sha }}

    ### Pilot      
      - name: Build and push go-simp-pilot
        uses: docker/build-push-action@v2
        with:
          context: ./service/pilot
          push: true
          tags: justhumanz/go-simp-pilot:latest
          build-args: |
            BASE_IMAGE=justhumanz/go-simp:${{ github.sha }}

    ### Utility
      - name: Build and push go-simp-utility
        uses: docker/build-push-action@v2
        with:
          context: ./service/utility
          push: true
          tags: justhumanz/go-simp-utility:latest
          build-args: |
            BASE_IMAGE=justhumanz/go-simp:${{ github.sha }}          


  deploy:
    needs: build
    environment:
      name: production    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
         
      - name: SSH and deploy to server
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          command: |
            export TOPGG=${{ env.TOPGG }}
            cd Go-Simp/swarm
            sudo git pull
            docker stack deploy -c main.yaml engine --with-registry-auth