name: build & deploy manual

on: 
  workflow_dispatch:
    inputs:
      imageName:
        description: 'docker image name'     
        required: true
        default: 'frontend'
      versionTag:
        description: 'new version of this build'
        required: true  
        default: 'latest'
      dirService:
        description: 'directory of service'
        required: true  
        default: './service/frontend/'         
      serviceName:
        description: 'service name on docker service'     
        required: true
        default: 'utility_frontend'      
jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push ${{ github.event.inputs.imageName }}
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.event.inputs.dirService }}
          push: true
          tags: justhumanz/go-simp-${{ github.event.inputs.imageName }}:${{ github.event.inputs.versionTag }}          


  deploy:
    needs: build_image  
    environment:
      name: production    
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - 
        name: SSH and deploy to server
        uses: fifsky/ssh-action@master
        with:
          host: go-simp.humanz.moe
          user: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd Go-Simp/swarm && git pull
            docker service update --image justhumanz/go-simp-${{ github.event.inputs.imageName }}:${{ github.event.inputs.versionTag }} ${{ github.event.inputs.serviceName }}
