name: Deploy to server

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, 
      # so your workflow can access it
      - uses: actions/checkout@master

      # Copying files and artifacts via SSH
      - name: SSH and deploy to server
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          connect_timeout: 20s
          first_ssh: |
            cd Go-Simp && git pull && sudo docker-compose -f docker-compose-prod.yaml build && sudo docker-compose -f docker-compose-prod.yaml up -d
