name: build & deploy go-simp modules manuals


on: 
  workflow_dispatch:
    inputs:
      versionTag:
        description: 'new version of this build'
        required: true  
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2        
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
       
      - name: Start build docker image
        run: echo ${{ github.event.inputs.versionTag }}        

    ## Build main image
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: justhumanz/go-simp:${{ github.sha }}

    #### Fanart    
      
      - name: Build and push bilibili fanart
        uses: docker/build-push-action@v2
        with:
          context: ./service/fanart/bilibili/
          push: true
          tags: justhumanz/go-simp-bilibili-fanart:${{ github.event.inputs.versionTag }}
          build-args: |
            BASE_IMAGE=justhumanz/go-simp:${{ github.sha }}          
      
      - name: Build and push twitter fanart
        uses: docker/build-push-action@v2
        with:
          context: ./service/fanart/twitter/
          push: true
          tags: justhumanz/go-simp-twitter-fanart:${{ github.event.inputs.versionTag }}
          build-args: |
            BASE_IMAGE=justhumanz/go-simp:${{ github.sha }}          
      
      - name: Build and push pixiv fanart
        uses: docker/build-push-action@v2
        with:
          context: ./service/fanart/pixiv/
          push: true
          tags: justhumanz/go-simp-pixiv-fanart:${{ github.event.inputs.versionTag }}
          build-args: |
            BASE_IMAGE=justhumanz/go-simp:${{ github.sha }}          


      ### Live
      
      - name: Build and push space bilibili livestream
        uses: docker/build-push-action@v2
        with:
          context: ./service/livestream/bilibili/space/
          push: true
          tags: justhumanz/go-simp-bilispace-livestream:${{ github.event.inputs.versionTag }}
          build-args: |
            BASE_IMAGE=justhumanz/go-simp:${{ github.sha }}           
      
      - name: Build and push live bilibili livestream 
        uses: docker/build-push-action@v2
        with:
          context: ./service/livestream/bilibili/live/
          push: true
          tags: justhumanz/go-simp-bililive-livestream:${{ github.event.inputs.versionTag }}
          build-args: |
            BASE_IMAGE=justhumanz/go-simp:${{ github.sha }}           

      
      - name: Build and push youtube checker livestream
        uses: docker/build-push-action@v2
        with:
          context: ./service/livestream/youtube/UpcomingChecker/
          push: true
          tags: justhumanz/go-simp-youtube-checker-livestream:${{ github.event.inputs.versionTag }}
          build-args: |
            BASE_IMAGE=justhumanz/go-simp:${{ github.sha }}           
      
      - name: Build and push youtube counter livestream
        uses: docker/build-push-action@v2
        with:
          context: ./service/livestream/youtube/UpcomingCounter/
          push: true
          tags: justhumanz/go-simp-youtube-counter-livestream:${{ github.event.inputs.versionTag }}
          build-args: |
            BASE_IMAGE=justhumanz/go-simp:${{ github.sha }}           

      - name: Build and push youtube PastTracker livestream
        uses: docker/build-push-action@v2
        with:
          context: ./service/livestream/youtube/PastTracker/
          push: true
          tags: justhumanz/go-simp-youtube-past-tracker-livestream:${{ github.event.inputs.versionTag }}
          build-args: |
            BASE_IMAGE=justhumanz/go-simp:${{ github.sha }}      

      - name: Build and push youtube LiveTracker livestream
        uses: docker/build-push-action@v2
        with:
          context: ./service/livestream/youtube/LiveTracker/
          push: true
          tags: justhumanz/go-simp-youtube-live-tracker-livestream:${{ github.event.inputs.versionTag }}
          build-args: |
            BASE_IMAGE=justhumanz/go-simp:${{ github.sha }}      

      - name: Build and push twitch livestream
        uses: docker/build-push-action@v2
        with:
          context: ./service/livestream/twitch/
          push: true
          tags: justhumanz/go-simp-twitch-livestream:${{ github.event.inputs.versionTag }}
          build-args: |
            BASE_IMAGE=justhumanz/go-simp:${{ github.sha }}            

      ### Subscriber
      
      - name: Build and push bilibili subs watcher
        uses: docker/build-push-action@v2
        with:
          context: ./service/subscriber/bilibili/
          push: true
          tags: justhumanz/go-simp-subscriber-bilibili:${{ github.event.inputs.versionTag }}
          build-args: |
            BASE_IMAGE=justhumanz/go-simp:${{ github.sha }}

      - name: Build and push twitch subs watcher
        uses: docker/build-push-action@v2
        with:
          context: ./service/subscriber/twitch/
          push: true
          tags: justhumanz/go-simp-subscriber-twitch:${{ github.event.inputs.versionTag }}
          build-args: |
            BASE_IMAGE=justhumanz/go-simp:${{ github.sha }}

      - name: Build and push twitter subs watcher
        uses: docker/build-push-action@v2
        with:
          context: ./service/subscriber/twitter/
          push: true
          tags: justhumanz/go-simp-subscriber-twitter:${{ github.event.inputs.versionTag }}
          build-args: |
            BASE_IMAGE=justhumanz/go-simp:${{ github.sha }}

      - name: Build and push youtube subs watcher
        uses: docker/build-push-action@v2
        with:
          context: ./service/subscriber/youtube/
          push: true
          tags: justhumanz/go-simp-subscriber-youtube:${{ github.event.inputs.versionTag }}
          build-args: |
            BASE_IMAGE=justhumanz/go-simp:${{ github.sha }}

      ### REST API
      
      - name: Build and push rest api
        uses: docker/build-push-action@v2
        with:
          context: ./service/rest-api/
          push: true
          tags: justhumanz/go-simp-rest_api-v2:${{ github.event.inputs.versionTag }}
          build-args: |
            BASE_IMAGE=justhumanz/go-simp:${{ github.sha }}          

      ### Frontend
      
      - name: Build and push fe
        uses: docker/build-push-action@v2
        with:
          context: ./service/frontend/
          push: true
          tags: justhumanz/go-simp-frontend:${{ github.event.inputs.versionTag }}
          build-args: |
            BASE_IMAGE=justhumanz/go-simp:${{ github.sha }}          

      ### Web admin api
      
      - name: Build and push web admin
        uses: docker/build-push-action@v2
        with:
          context: ./service/web-admin-api
          push: true
          tags: justhumanz/go-simp-web-admin-api:latest       

      ### Web admin vue
      
      - name: Build and push web admin
        uses: docker/build-push-action@v2
        with:
          context: ./service/web-admin-vue
          push: true
          tags: justhumanz/go-simp-web-admin-vue:latest                

      ### Go simp web
      
      - name: Build and push web admin
        uses: docker/build-push-action@v2
        with:
          context: ./service/new-web-vue
          push: true
          tags: justhumanz/go-simp-web-vue-v2:latest      

  deploy:
    needs: build  
    environment:
      name: production    
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: SSH and deploy to server
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          command: |
            export RELEASE_VERSION=${{ github.event.inputs.versionTag }}
            export TOPGG=${{ secrets.TOPGG }}
            export BOT_SECRET=${{ secrets.SECRET }}
            export BOT_CLIENTID=${{ secrets.CLIENTID }}
            export BOT=${{ secrets.BOT }}
            export DB_PASS=${{ secrets.DB_PASS }}

            cd Go-Simp/swarm && git pull
            docker stack deploy -c live.yaml livestream --with-registry-auth
            docker stack deploy -c fanart.yaml fanart --with-registry-auth
            docker stack deploy -c utility.yaml utility --with-registry-auth