FROM node:alpine

RUN apk add --update --no-cache git
RUN mkdir /app
WORKDIR /app
RUN git clone --single-branch --branch main https://github.com/JustHumanz/Go-Simp
RUN git checkout main
WORKDIR Go-Simp/service/rest-api/
RUN npm install

CMD ["node", "index.js"]
