FROM node:alpine

RUN apk add --update --no-cache git
RUN mkdir /app
WORKDIR /app
RUN git clone https://github.com/JustHumanz/Go-Simp
WORKDIR Go-Simp/service/rest-api/
RUN npm install

CMD ["node", "index.js"]
